version: "3.3"
services:
  chat-websocket:
    container_name: elite-militar
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install ts-node && npm install && npm run start-dev"
